<?php require('template/header.phtml') ?>

    <div id="content">

        <?php echo $message ?>
                <h3>Adverts</h3>
<!--                <p>--><?php //echo $view->itemID ?><!--</p>-->
                <table class="table table-hover">
                    <thead>
<!--                    <col width="18%">-->
<!--                    <col width="18%">-->
<!--                    <col width="18%">-->
<!--                    <col width="18%">-->
<!--                    <col width="28%">-->
                    <tr><th>Title</th><th>Added</th><th>Price</th><th>Picture</th><th>Delete</th><th>Edit</th></tr>


                    </thead>
                    <tbody>
                    <?php foreach ($view->usersItems as $carsData) { ?>
    <?php $id = $carsData->getID(); ?>
    <?php $pics = $view->pictureSet->getPicsByItemID($carsData->getID()) ;?>
    <tr>
        <td><?php echo $carsData->getTitle() ?></td>
        <td><?php echo $carsData->getAdded() ?></td>
        <td><?php echo $carsData->getPrice() ?></td>
        <td><img src="uploads/<?php echo $pics[0] ?>" width="75px" /></td>
        <td><form  method="post" action="manageAds.php" >
                <input type="hidden" name="id"  />
                <button name="deleteAd" type="submit" class="btn btn-danger" value="  <?php echo $id ?>  ">Delete</button>
            </form>
        </td>
        <td><form  method="post" action="editAdvert.php?id=<?php echo $id?>" >
                <input type="hidden" name="id"  />
                <button name="editAd" type="submit" class="btn btn-info" value="  <?php echo $id ?>  ">Edit</button>
            </form>
        </td>
    </tr>
                    <?php } ?>





<!--//                        $id = $carsData->getID();-->
<!--//                        $pics = $view->pictureSet->getPicsByItemID($carsData->getID());-->
<!--//                        $string = "<form method=\"post\" action=\"manageAds.php\">-->
<!--//                <button id=\"delBManage\" name=\"deleteAd\" type=\"submit\" class=\"btn btn-danger\" value=\"  $id  \">Delete</button>-->
<!--//                -->
<!--//            </form><form method=\"post\" action=\"manageAds.php\">-->
<!--//                <button name=\"editAd\" type=\"submit\" class=\"btn btn-info\" value=\"edit\">Edit</button>-->
<!--//            </form>";-->
<!--//                        echo '<tr> <td>' . $carsData->getTitle() . '</td> <td>' . $carsData->getAdded() . '</td> <td>' . $carsData->getPrice() . '</td> <td>' . '<img src="uploads/' . $pics[0] . ' " width="75px" />' . '-->
<!--//                            </td><td>' . $string . '</td></tr>';-->
<!--//                    } ?>-->
                    </tbody>

                </table>



    </div>
</div>




<?php require('template/footer.phtml') ?>

