<?php require('template/header.phtml') ?>

<div id="content">



    <div id="index">


        <?php foreach ($searchedCars as $carsData) { ?>
        <a href="advert.php?id=<?php echo $carsData->getId() ?>">

            <div class="element">
                <?php $pics = $view->pictureSet->getPicsByItemID($carsData->getID()); ?>
                <div id="picture"><img src="uploads/<?php echo $pics[0] ;?>" width="100%" height="250px"></div>
                <p id="pTitle"><?php echo $carsData->getTitle()?></p>
                <p>£ <?php echo $carsData->getPrice()?></p>
                <p>Mileage: <?php echo $carsData->getMileage()?></p>
                <!--                <p>Engine: --><?php //echo $carsData->getEngine()?><!--</p>-->
                <!--                <p>Color: --><?php //echo $carsData->getColor()?><!--</p>-->
                <!--                <p>Gearbox: --><?php //echo $carsData->getGearbox()?><!--</p>-->
                <!--                <p>Mileage: --><?php //echo $carsData->getMileage()?><!-- miles</p>-->
                <!--                <p>Description: --><?php //echo $carsData->getDescription()?><!--</p>-->
            </div>
        </a>
            <?php } ?>



    </div>


</div>



<?php require('template/footer.phtml') ?>
