<?php require('template/header.phtml') ?>
<div id="content">
    <div class="login">
        <div class="header">
            <h2>Update user details</h2>
        </div>

        <form class="submitForms" method="post" action="editUser.php">
            <?php if(isset($_POST['registerButton'])) {
                include('errors.php');
            }
            ?>
            <div class="input-group">
                <label>User name</label>
                <input type="text" name="username" value="<?php echo $usernameForm; ?>">
            </div>
            <div class="input-group">
                <label>Email</label>
                <input type="text" name="email" value="<?php echo $mailForm; ?>">
            </div>
            <div class="input-group">
                <label>Phone number</label>
                <input type="text" name="phoneNo" value="<?php echo $phoneForm; ?>">
            </div>
            <div class="input-group">
                <label>Address</label>
                <input type="text" name="address" value="<?php echo $addressForm; ?>">
            </div>
            <div class="input-group">
                <label>Post Code</label>
                <input type="text" name="postCode" value="<?php echo $postcodeForm; ?>">
            </div>
            <div class="input-group">
                <label>City</label>
                <input type="text" name="city" value="<?php echo $cityForm; ?>">
            </div>

            <div class="input-group">
                <button type="submit" name="updateUsrButton" class="btn btn-success">Update</button>
            </div>

        </form>

    </div>
</div>




<?php require('template/footer.phtml') ?>

